### ISSUE TITLE
No registered namespace for type net.biz.digitalPropertyNetwork.RegisterPropertyForSale

### ISSUE THREAD

**Issue by opiepj** [fabric-composer/sample-networks#27]
From the composer CLI, when running:

`composer archive create --sourceName digitalproperty-network --sourceType module --archiveFile digitalPropertyNetwork.bna`

I'm getting:
**No registered namespace for type net.biz.digitalPropertyNetwork.RegisterPropertyForSale**

**Comment by jthub** [comment]
This should have been fixed in the latest release https://github.com/fabric-composer/fabric-composer/releases/tag/v0.5.10
